version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://dbtodo_nysz_user:YSBHe0ETyzzEkXcNwVq1ckY5X9nRKIfr@dpg-ct7jtp08fa8c73bs91n0-a/dbtodo_nysz

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c fsync=off

volumes:
  db_data:
